print("'Hello World' is how you say hello world in english")
print("'Γειά σου Κόσμε' is how you say hello world in greek")
print("'Olá Mundo' is how you say hello world in portuguese")
print("'Ahoj světe' is how you say hello world in czech")
print("'안녕 세상' is how you say hello world in korean")
print("'你好，世界' is how you say hello world in chinese")
print("'नमस्ते दुनिया' is how you say hello world in hindi")
print("'Salamu, Dunia' is how you say hello world in swahli")
print("'Witaj świecie' is how you say hello world in poland")
print("'Hola Mundo' is how you say hello world in spanish")
print("'ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ' is how you say hello world in leo")
